<a href="https://colab.research.google.com/github/n-prathyusha82/Numpy_problem-HackerRank-/blob/main/Numpy_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**pb-1:shape:
The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.
(a). Using shape to get array dimensions,
import numpy,
my__1D_array = numpy.array([1, 2, 3, 4, 5])
print my_1D_array.shape     #(5,) -> 1 row and 5 columns,
my__2D_array = numpy.array([[1, 2],[3, 4],[6,5]])
print my_2D_array.shape     #(3, 2) -> 3 rows and 2 columns,
(b). Using shape to change array dimensions.
import numpy and
change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
print change_array,     
Output:
[[1 2]
[3 4]
[5 6]]
reshape.
The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.
import numpy and
my_array = numpy.array([1,2,3,4,5,6])
print numpy.reshape(my_array,(3,2)),
Output:
[[1 2]
[3 4]
[5 6]]
Task:
You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.
Input Format:
A single line of input containing  space separated integers.
Output Format:
Print the X NumPy array.
Sample Input:
1 2 3 4 5 6 7 8 9
Sample Output
[[1 2 3]
 [4 5 6]
 [7 8 9]]**

In [ ]:
import numpy as np

arr = np.array(input().split(), int)
print(np.reshape(arr, (3, 3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**pb-2:Transpose:
We can generate the transposition of an array using the tool numpy.transpose.
It will not affect the original array, but it will create a new array.
import numpy and
my_array = numpy.array([[1,2,3],[4,5,6]])
print numpy.transpose(my_array),
Output:
[[1 4]
 [2 5]
 [3 6]]
Flatten,
The tool flatten creates a copy of the input array flattened to one dimension.
import numpy,
my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print my_array.flatten(),
Output:
[1 2 3 4 5 6]
Task:
You are given a X integer array matrix with space separated elements ( = rows and  = columns).
Your task is to print the transpose and flatten results.
Input Format:
The first line contains the space separated values of  and.
The next  lines contains the space separated elements of  columns.
Output Format:
First, print the transpose array and then print the flatten.
Sample Input:
2 2
1 2
3 4
Sample Output:
[[1 3]
 [2 4]]
[1 2 3 4]**

In [ ]:
import numpy as np

n, m = map(int, input().split())
arr = np.array([input().split() for _ in range(n)], int)

print(np.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


**pb-3:Concatenate:
Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined:
import numpy,
array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9]),
print numpy.concatenate((array_1, array_2, array_3)),  
Output:
[1 2 3 4 5 6 7 8 9]
If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. By default, it is along the first dimension.
import numpy,
array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])
print numpy.concatenate((array_1, array_2), axis = 1)   
Output:
[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]    
Task:
You are given two integer arrays of size X and X ( &  are rows, and  is the column). Your task is to concatenate the arrays along axis 0.
Input Format:
The first line contains space separated integers ,  and 0.
The next  lines contains the space separated elements of the  columns.
After that, the next  lines contains the space separated elements of the  columns.
Output Format:
Print the concatenated array of size X.
Sample Input:
4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
Sample Output:
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]**

In [ ]:
import numpy as np

n, m, p = map(int, input().split())
arr1 = np.array([input().split() for _ in range(n)], int)
arr2 = np.array([input().split() for _ in range(m)], int)
print(np.concatenate((arr1, arr2), axis=0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


**pb-4:zeros,
The zeros tool returns a new array with a given shape and type filled with 0's.
import numpy,
print numpy.zeros((1,2))#Default type is float
Output:[[ 0.  0.]],
print numpy.zeros((1,2), dtype = numpy.int) #Type changes to int
Output:[[0 0]]
ones,
The ones tool returns a new array with a given shape and type filled with 1's.
import numpy
print numpy.ones((1,2))#Default type is float
Output:[[ 1.  1.]],
print numpy.ones((1,2), dtype = numpy.int) #Type changes to int
Output:[[1 1]]   
Task:
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.
Input Format:
A single line containing the space-separated integers.
Constraints:
Output Format:
First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.
Sample Input 0:
3 3 3
Sample Output 0:
[[[0 0 0]
  [0 0 0]
  [0 0 0]]
[[0 0 0]
  [0 0 0]
  [0 0 0]]
[[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]
[[1 1 1]
  [1 1 1]
  [1 1 1]]
[[1 1 1]
  [1 1 1]
  [1 1 1]]]
Explanation 0:
Print the array built using numpy.zeros and numpy.ones tools and you get the result as shown.**

In [ ]:
import numpy as np

shape = tuple(map(int, input().split()))
print(np.zeros(shape, dtype=int))
print(np.ones(shape, dtype=int))


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


**pb-5:identity:
The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as  and the rest as . The default type of elements is float.
import numpy
print numpy.identity(3) #3 is for  dimension 3 X 3
Output:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
eye,
The eye tool returns a 2-D array with 's as the diagonal and 's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter . A positive  is for the upper diagonal, a negative  is for the lower, and a   (default) is for the main diagonal.
import numpy,
print numpy.eye(8, 7, k = 1)    # 8 X 7 Dimensional array with first upper diagonal 1.
Output:
[[ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
print numpy.eye(8, 7, k = -2)   # 8 X 7 Dimensional array with second lower diagonal 1.
Task:
Your task is to print an array of size X with its main diagonal elements as 's and 's everywhere else.
Note:
In order to get alignment correct, please insert the line  below the numpy import.
Input Format:
A single line containing the space separated values of and.
denotes the rows,
denotes the columns.
Output Format:
Print the desired X array.
Sample Input:
3 3
Sample Output:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]**

In [ ]:
import numpy as np

n, m = map(int, input().split())
print(np.eye(n, m))


3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**6.You are given two integer arrays A, and B of dimensions X.
Your task is to perform the following operations:
Add( + )
Subtract( - )
Multiply( * )
Integer Division( / )
Mod( % )
Power( ** )
Note:
There is a method numpy.floor_divide() that works like numpy.divide() except it performs a floor division.
Input Format:
The first line contains two space separated integers,M and N.
The next  lines contains space separated integers of array.
The following  lines contains space separated integers of array.
Output Format:
Print the result of each operation in the given order under Task.
Sample Input:
1 4
1 2 3 4
5 6 7 8
Sample Output:
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
Use // for division in Python 3.**

In [1]:
import numpy as np
n, m = map(int, input().split())
A = np.array([list(map(int, input().split())) for _ in range(n)])
B = np.array([list(map(int, input().split())) for _ in range(n)])
print(np.add(A, B))
print(np.subtract(A, B))
print(np.multiply(A, B))
print(np.floor_divide(A, B))
print(np.mod(A, B))
print(np.power(A, B))


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


**7.Task:
You are given a 1-D array, . Your task is to print the ,  and  of all the elements of.
Note:
In order to get the correct output format, add the line  below the numpy import.
Input Format:
A single line of input containing the space separated elements of array .
Output Format:
On the first line, print the  of A.
On the second line, print the  of A.
On the third line, print the  of A.
Sample Input:
1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
Sample Output:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]**

In [2]:
import numpy as np
np.set_printoptions(legacy='1.13')
A = np.array(list(map(float, input().split())))
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


**8.Task:
You are given a 2-D array with dimensions X.
Your task is to perform the min function over axis  and then find the max of that.
Input Format:
The first line of input contains the space separated values of  and .
The next  lines contains  space separated integers.
Output Format:
Compute the min along axis  and then print the max of that result.
Sample Input:
4 2
2 5
3 7
1 3
4 0
Sample Output:
3**

In [3]:
import numpy as np

n, m = map(int, input().split())
array = np.array([list(map(int, input().split())) for _ in range(n)])

print(np.max(np.min(array, axis=1)))


4 2
2 5
3 7
1 3
4 0
3


**9.Task:
You are given a 2-D array of size X.
Your task is to find:
The mean along axis
The var along axis
The std along axis
Input Format:
The first line contains the space separated values of  and .
The next  lines contains  space separated integers.
Output Format:
First, print the mean.
Second, print the var.
Third, print the std.
Sample Input:
2 2
1 2
3 4
Sample Output:
[ 1.5  3.5]
[ 1.  1.]
1.11803398875**

In [4]:
import numpy as np

n, m = map(int, input().split())
arr = np.array([input().split() for _ in range(n)], int)

print(np.mean(arr, axis=1))
print(np.var(arr, axis=0))
print(round(np.std(arr), 11))


2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


**10.Task:
You are given a 2-D array with dimensions X.
Your task is to perform the  tool over axis  and then find the  of that result.
Input Format:
The first line of input contains space separated values of  and .
The next  lines contains  space separated integers.
Output Format:
Compute the sum along axis . Then, print the product of that sum.
Sample Input:
2 2
1 2
3 4
Sample Output:
24**

In [5]:
import numpy as np
N, M = map(int, input().split())
array = np.array([list(map(int, input().split())) for _ in range(N)])
result = np.prod(np.sum(array, axis=0))
print(result)

2 2
1 2
3 4
24


**11.Task:
You are given two arrays  and . Both have dimensions of X.
Your task is to compute their matrix product.
Input Format:
The first line contains the integer .
The next  lines contains  space separated integers of array .
The following  lines contains  space separated integers of array .
Output Format:
Print the matrix multiplication of  and .
Sample Input:
2
1 2
3 4
1 2
3 4
Sample Output:
[[ 7 10]
 [15 22]]**

In [6]:
import numpy as np
n = int(input())
A = np.array([input().split() for _ in range(n)], int)
B = np.array([input().split() for _ in range(n)], int)
print(np.dot(A, B))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


**12.Task:
You are given two arrays:  and .
Your task is to compute their inner and outer product.
Input Format:
The first line contains the space separated elements of array .
The second line contains the space separated elements of array .
Output Format:
First, print the inner product.
Second, print the outer product.
Sample Input:
0 1
2 3
Sample Output:
3
[[0 0]
 [2 3]]**

In [7]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A, B))
print(np.outer(A, B))


0 1
2 3
3
[[0 0]
 [2 3]]


**13.Task:
You are given the coefficients of a polynomial .
Your task is to find the value of  at point.
Input Format:
The first line contains the space separated value of the coefficients in .
The second line contains the value of .
Output Format:
Print the desired value.
Sample Input:
1.1 2 3
0
Sample Output:
3.0**

In [8]:
import numpy as np
coefficient = np.array(input().split(), float)
x = float(input())
print(np.polyval(coefficient, x))

1.1 2 3
0
3.0


**14.Task:
You are given a square matrix  with dimensions X. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.
Input Format:
The first line contains the integer .
The next  lines contains the  space separated elements of array .
Output Format:
Print the determinant of .
Sample Input:
2
1.1 1.1
1.1 1.1
Sample Output:
0.0**

In [10]:
import numpy as np

n = int(input())
matrix = np.array([input().split() for _ in range(n)], float)

determinant = np.linalg.det(matrix)
print(round(determinant, 2))


2
1.1 1.1
1.1 1.1
0.0
